force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <label>Journal</label>
    <nameField>
        <displayFormat>J#{000000000}</displayFormat>
        <label>Journal #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger_Line__c/Ledger_Line__c.object-meta.xml
<CustomObject>
    <label>Ledger Line</label>
    <nameField>
        <displayFormat>L#{0000000000}</displayFormat>
        <label>Ledger #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger_Line__c/fields/Credit_Debit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Debit__c</fullName>
    <label>Credit / Debit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ledger_Line__c/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Ledger Lines</relationshipLabel>
    <relationshipName>Ledger_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ledger_Line__c/fields/Ledger__c.field-meta.xml
<CustomField>
    <fullName>Ledger__c</fullName>
    <label>Ledger</label>
    <referenceTo>Ledger__c</referenceTo>
    <relationshipLabel>Ledger Lines</relationshipLabel>
    <relationshipName>Ledger_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JournalHandler.cls
public without sharing class JournalHandler extends TriggerHandlerUtilities {
    
    public override void beforeDelete(List<SObject> o, Map<Id, SObject> oMap, List<SObject> n, Map<Id, SObject> nMap, Schema.SObjectType sot, Boolean debug)
    {
        Map<String,Map<Id,Map<String,Decimal>>> ledgerLineMap = new Map<String,Map<Id,Map<String,Decimal>>>();
        for(Ledger_Line__c ledgerLine : [SELECT Id, Amount__c, Credit_Debit__c, Ledger__c FROM Ledger_Line__c WHERE Journal__c IN: oMap.keySet()]) {
            LedgerLineHandler.HandleAdjustment(ledgerLineMap,'Ledger',ledgerLine.Ledger__c,ledgerLine.Credit_Debit__c,0-ledgerLine.Amount__c);
        }
        LedgerLineHandler.HandleCalculations(ledgerLineMap);
    }
}