force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <label>Journal</label>
    <nameField>
        <displayFormat>J#{000000000}</displayFormat>
        <label>Journal #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal__c/fields/Debit__c.field-meta.xml
<CustomField>
    <fullName>Debit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Credit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ledger_Line__c/Ledger_Line__c.object-meta.xml
<CustomObject>
    <label>Ledger Line</label>
    <nameField>
        <displayFormat>L#{0000000000}</displayFormat>
        <label>Ledger #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger_Line__c/fields/Credit_Debit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Debit__c</fullName>
    <label>Credit / Debit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ledger_Line__c/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Ledger Lines</relationshipLabel>
    <relationshipName>Ledger_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ledger_Line__c/fields/Ledger__c.field-meta.xml
<CustomField>
    <fullName>Ledger__c</fullName>
    <label>Ledger</label>
    <referenceTo>Ledger__c</referenceTo>
    <relationshipLabel>Ledger Lines</relationshipLabel>
    <relationshipName>Ledger_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LedgerLineHandler.cls
public without sharing class LedgerLineHandler extends TriggerHandlerUtilities  {
    
    public override void afterInsert(List<SObject> o, Map<Id, SObject> oMap, List<SObject> n, Map<Id, SObject> nMap, Schema.SObjectType sot, Boolean debug)
    {
        validateRecords((List<Ledger_Line__c>)n,new Map<Id,Ledger_Line__c>());
    }

    public override void afterUpdate(List<SObject> o, Map<Id, SObject> oMap, List<SObject> n, Map<Id, SObject> nMap, Schema.SObjectType sot, Boolean debug)
    {
        validateRecords((List<Ledger_Line__c>)n,(Map<Id,Ledger_Line__c>)oMap);
    }


    private static void validateRecords(List<Ledger_Line__c> newLines, Map<Id,Ledger_Line__c> oldLines) {

        List<Ledger_Line__c> validLines = new List<Ledger_Line__c>();
        Map<Id,Decimal> lineAdjustmentMap = new Map<Id,Decimal>();

        for(Ledger_Line__c line : newLines) {
            if(!oldLines.containsKey(line.Id)) {
                validLines.add(line);
                continue;
            }

            if(oldLines.get(line.Id).Amount__c == line.Amount__c) continue;
            validLines.add(line);
            lineAdjustmentMap.put(line.Id,line.Amount__c - oldLines.get(line.Id).Amount__c);
        }

        if(validLines.isEmpty()) return;

        UpdateCalculations(validLines,lineAdjustmentMap);
    }

    private static void UpdateCalculations(List<Ledger_Line__c> newLines, Map<Id,Decimal> lineAdjustmentMap) {
        
        Map<String,Set<Id>> parentIdMap = new Map<String,Set<Id>>{
            'Ledger' => new Set<Id>(),
            'Journal' => new Set<Id>()
        };
        for(Ledger_Line__c line : newLines) {
            parentIdMap.get('Ledger').add(line.Ledger__c);
            parentIdMap.get('Journal').add(line.Journal__c);
        }

        Map<Id,Ledger__c> ledgerMap = new Map<Id,Ledger__c>([
            SELECT Id, Credit__c, Debit__c FROM Ledger__c WHERE Id IN :parentIdMap.get('Ledger')
        ]);
        Map<Id,Journal__c> journalMap = new Map<Id,Journal__c>([
            SELECT Id, Credit__c, Debit__c FROM Journal__c WHERE Id IN :parentIdMap.get('Journal')
        ]);

        for(Ledger_Line__c line : newLines) {
            Ledger__c ledger = ledgerMap.get(line.Ledger__c);
            Journal__c journal = journalMap.get(line.Journal__c);

            Decimal value = lineAdjustmentMap.containsKey(line.Id) ? lineAdjustmentMap.get(line.Id) : line.Amount__c;

            if(line.Credit_Debit__c == 'Credit') {
                ledger.Credit__c += value;
                journal.Credit__c += value;
            } else {
                ledger.Debit__c += value;
                journal.Debit__c += value;
            }

            ledgerMap.put(ledger.Id,ledger);
            journalMap.put(journal.Id,journal);
        }

        update new List<Ledger__c>(ledgerMap.values());
        update new List<Journal__c>(journalMap.values());
    }
}